### ISSUE TITLE
Switch to mailjet transactional service

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/email#3]
Config has to go into consul, so that we can dynamically change it.
(This requires using config.getProperty every time we send an email)

We also need to make it transactional, as currently email sending doesnt propagate any errors up, in case email is not sent or got bounced.

We should set this up asynchronously,
e.g.
service calls email api to send email and will include a callback uri

email service will call callback uri once the email is delivery / bounced

**Comment by sureshvarman-cronj** [comment]
**email service will call callback uri once the email is delivery / bounced** Need to be done, to call the callback url.
